#!/bin/bash

# Exports

# Make some commands not show up in history
export HISTIGNORE="ls:ls *:cd:cd -:pwd;exit:date:* --help"

# Move to the beginning of PATH so that it always take precedence over /usr/bin
if [ -d "/usr/local/bin" ]; then
    PATH="/usr/local/bin:$PATH"
fi

declare -a bins=(
    "/usr/bin"
    "$HOME/bin"
    "$HOME/dotfiles/bin"
    "$(brew --prefix coreutils)/libexec/gnubin" # Add brew-installed GNU core utilities bin
    "$(brew --prefix)/share/npm/bin" # Add npm-installed package bin
)

# If these bins exist, then add them to the PATH
for index in ${!bins[*]}
do
    if [ -d ${bins[$index]} ]; then
        PATH="$PATH:${bins[$index]}"
    fi
done

unset bins

export PATH
